import torch
from sklearn.metrics import confusion_matrix, classification_report
from dataset import load_shadowtrace_data
from model import ShadowTraceGNN

# Load data and initialize model architecture
data = load_shadowtrace_data('outputs/nodes.csv', 'outputs/edges.csv')
model = ShadowTraceGNN(in_channels=data.x.shape[1], hidden_channels=64)

# Load the trained weights generated by train.py
model.load_state_dict(torch.load('shadowtrace.pt'))
model.eval()

# Generate predictions strictly on the unseen test set
with torch.no_grad():
    out = model(data.x, data.edge_index)
    # Apply sigmoid to convert raw logits to probabilities, threshold at 0.5
    preds = (torch.sigmoid(out[data.test_mask]) > 0.5).cpu().numpy()
    y_true = data.y[data.test_mask].cpu().numpy()

# Calculate and display the metrics
cm = confusion_matrix(y_true, preds)

print("=== CONFUSION MATRIX ===")
print(f"True Negatives (Correct Licit):   {cm[0][0]}")
print(f"False Positives (False Alarms):   {cm[0][1]}")
print(f"False Negatives (Missed Illicit): {cm[1][0]}")
print(f"True Positives (Caught Illicit):  {cm[1][1]}\n")

print("=== CLASSIFICATION REPORT ===")
print(classification_report(y_true, preds, target_names=["Licit (0)", "Illicit (1)"], zero_division=0))